### ISSUE TITLE
Client Server connection

### ISSUE THREAD

**Issue by aalnaw2s** [rnatar609/ASTT-RoboCup-At-Work#11]
if we :
1. run the RefereeSystem. then
2. run a Client instance. and it is connected to the server.
3. then if we terminate the Client before sending the specification. the Server status appears that the client is still connected to it and the task specification could not be sent.
   4.if we run a new Client instance it give us that it is connected to the server and when we try to send the task specification we have this exception:

Exception in thread "AWT-EventQueue-0" org.zeromq.ZMQException: Operation cannot be accomplished in current state(0x9523dfb)
    at org.zeromq.ZMQ$Socket.send(Native Method)
    at model.TaskServer.sendTaskSpecToClient(TaskServer.java:85)
    at controller.MainController$11.actionPerformed(MainController.java:269)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by janpaulus** [comment]
I can not reproduce this issue. I do not get the Exception. Try with the newest version.

**Comment by aalnaw2s** [comment]
i tried it again with the new version and it grave me the same. i tried two scenarios :

First:
=> start referee
=> start client
=> stop client (force terminated before timer start on referee). still appears connected on referee side.
=> start client again.
=> start timer on referee and try to send specs to client. here we need to click on send specs twice
at first the message :
String sent to client: BMT<D0,D1,O1,line(nut),S1>
Could not send the task specification to the team: b-it-bots

at second it is done.
String sent to client: BMT<D0,D1,O1,line(nut),S1>
Message from b-it-bots: ACK

Second:
=> start referee
=> start client
=> stop client (force terminated after timer start on referee). still appears connected on referee side.
=> try to send specs on referee side the the message twice

at first we have
String sent to client: BMT<D0,D1,O1,line(nut),S1>
Could not send the task specification to the team: b-it-bots

at second the exception appears.

=> even if after the first specs sending trial we start a client again then we try to send specs again, the exception still appears.

Regards,
